server:
    port: 8050
    servlet:
        session:
            cookie:
                domain: .bob.com    # ‚Üê note the leading dot
spring:
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:mysql://192.168.101.65:3306/mall-wms?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.101.65:8848
#                ip: 168.5.59.205 # public local net, needs to be modified constantly
                port: 8050
        alibaba:
            seata:
                tx-service-group: mall-ware-group
        sentinel:
            transport:
                #                client-ip: 192.168.101.1
                dashboard: 192.168.101.65:8858
                port: 8719
            log:
                dir: /data/logs/sentinel

    application:
        name: mall-ware

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto

management:
    endpoints:
        web:
            exposure:
                include: '*'

